name: mufan-code-CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request_review:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: node:18
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn test
